### ISSUE TITLE
Add B0 and/or B1 correction for SIR-FSE

### ISSUE THREAD

**Issue by vuongmanhtung** [neuropoly/qMTLab#19]
Hi,
I see we dont take into account B0/B1 correction for SIRFSE, I looked in the model and feel that B1 can affect how we compute Sr as follows:
File: computeSr.m
InvPulse   = GetPulse(180,0,Trf,PulseShape);

Also if we assume the Gaussian lineshape, B0 may have some effect because the offset may not be zero.
 Do you see anywhere that relates to B0/B1 as well? Could you please add B0/B1 correction into the codes?

I know it is less complicated to make some assumption but it is great if we can investigate how much B0/B1correction affects the fitting results. Then using B0/B1map or not is up to the users.

**Comment by mathieuboudreau** [comment]
Hi Vuong,

I'm not experienced in using the SIR qMT method, however re-checking a recent paper at 3T (1.	Dortch RD, Li K, Gochberg DF, et al. Quantitative magnetization transfer imaging in human brain at 3 T via selective inversion recovery. Magn Reson Med 2011;66(5):1346-1352.), the authors concluded insensitivity of SIRFSE qMT to B0/B1 inhomogeneities:

![dortch2011](https://cloud.githubusercontent.com/assets/1421029/19573099/6669fff4-96df-11e6-9220-9ae6af2ea769.png)

Unless there's been other published work suggesting a sensitivity of this method to B0/B1 inaccuracies, my personal opinion would be to omit the option in the package, to avoid new users from using this option. I've always been a fan of KISS principle when coding in general. The less options the user has, the easier it will be for them to use the software (and less likely they'll make mistakes, or acquiring data that they might not actually need for the study (B0/B1))

If you plan on exploring the B0/B1 sensitivity of SIRFSE for a study yourself (or know someone who wants it), then maybe I'd suggest forking the repo and creating an add-on that incorporates this functionality, the task shouldn't be too difficult. That way, once published, it could be incorporated into the main package easily.

Of course, if Jean-Francois or Tanguy feel that it should be incorporated, feel free to chime in!

**Comment by jfcabana** [comment]
Hello all, here was my reply to Tung email. I thought it would show up here also, but it seems not...

..........

Hello Tung,

The authors of the method do not consider B0/B1 inhomogeneities on Sr. The restricted pool lineshape is so broad that deviations in B would be negligeable. They are however taken into account for the free pool, by fitting directly for Sf. One of the advantage of the SIRFSE technique is indeed that it does not need an additional B1 or B0 map. 


We could of course add this effect in the computation of Sr if you want to investigate how it could affect the fitting. That should be straightforward. You probably just need to copy a few lines from the SPGR_fit function into SIRFSE_fit. Let me know if you need assistance with this. If you do this, then you should also modify the computation of Sf, as it could be computed directly instead of fitted.


Cheers,

JF

**Comment by vuongmanhtung** [comment]
Good points, thanks for your instant responses.

**Comment by jfcabana** [comment]
Hello Tung,

The authors of the method do not consider B0/B1 inhomogeneities on Sr. The restricted pool lineshape is so broad that deviations in B would be negligeable. They are however taken into account for the free pool, by fitting directly for Sf. One of the advantage of the SIRFSE technique is indeed that it does not need an additional B1 or B0 map.

We could of course add this effect in the computation of Sr if you want to investigate how it could affect the fitting. That should be straightforward. You probably just need to copy a few lines from the SPGR_fit function into SIRFSE_fit. Let me know if you need assistance with this. If you do this, then you should also modify the computation of Sf, as it could be computed directly instead of fitted.

Cheers,
JF



Sent from my Galaxy Tab® A


-------- Message d'origine --------
De : vuongmanhtung <notifications@github.com>
Date : 16-10-20 13:56 (GMT-05:00)
À : neuropoly/qMTLab <qMTLab@noreply.github.com>
Objet : [neuropoly/qMTLab] Add B0 and/or B1 correction for SIR-FSE (#19)


Hi,
I see we dont take into account B0/B1 correction for SIRFSE, I looked in the model and feel that B1 can affect how we compute Sr as follows:
File: computeSr.m
InvPulse = GetPulse(180,0,Trf,PulseShape);

Also if we assume the Gaussian lineshape, B0 may have some effect because the offset may not be zero.
Do you see anywhere that relates to B0/B1 as well? Could you please add B0/B1 correction into the codes?

I know it is less complicated to make some assumption but it is great if we can investigate how much B0/B1correction affects the fitting results. Then using B0/B1map or not is up to the users.

-
