### ISSUE TITLE
Fitting Panel: Use R1 map checkbox

### ISSUE THREAD

**Issue by mamclean** [neuropoly/qMTLab#24]
When using the "Use R1 map" checkbox, the Fix R1f checkbox is automatically checked.  This is misleading because it seems like R1f will be fixed to the value in the start column, rather than constrained by the R1 map provided.

It seems like a more natural use of this panel would be if the "Use R1 map" box was titled something like "Use R1map to constrain R1f" and the "Fix R1f" button was prevented from being checked simultaneously.
The fact that the Fix R1f button means different things in two different configurations is confusing, even after reading the manual section 5.3.

Thanks,
Melany Mclean

Biomedical Engineering, M.Sc. Candidate
Supervised by Dr. Bruce Pike

**Comment by mathieuboudreau** [comment]
I agree with Melany. Instead of the "Fix R1f" button automatically being checked after we check "Use R1 map", the opposite should happen (Fix R1f should get unchecked automatically when Fix R1 map gets checked). 

I found where in the code this behavior occurs, however I'm not sure if the if condition when you start the fitting with Fix R1map checks the bool for both checkboxes, or just Fix R1map.

**Comment by jfcabana** [comment]
Yes I agree this behavior can be confusing. 
Let me check how this should be fixed.

**Comment by jfcabana** [comment]
There you go! I changed it so you can only select either "Fix R1f" or "Use R1 map". Also applied the same logic to "Fix R1r" and "R1r = R1f". 

I also changed the labels to more descriptive "Use R1 map to constrain R1f" and "Fix R1r = R1f".

Does the make sense to you?

**Comment by mamclean** [comment]
Thank you. That will make a lot more sense as a user.

**Comment by jfcabana** [comment]
You're welcome! 

Please let me know again if you find anything that is unclear. Your feedback is quite useful.

Cheers,
JF
